/* Elysium FFI — auto-generated by cbindgen. Do not edit. */

#ifndef ELYSIUM_FFI_H
#define ELYSIUM_FFI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a running Elysium node. Heap-allocated; caller owns it.
 * Free with `elysium_stop`.
 */
typedef struct ElysiumHandle ElysiumHandle;

/**
 * Start an Elysium node. Returns an opaque handle or null on failure.
 *
 * - `port`: UDP listen port (0 = OS-assigned).
 * - `config_json`: optional JSON with bootstrap_peers, onion_mode, data_dir.
 */
struct ElysiumHandle *elysium_start(uint16_t port, const char *config_json);

/**
 * Stop the node and free all resources. Do not use `handle` after this call.
 */
void elysium_stop(struct ElysiumHandle *handle);

/**
 * Returns the node's ID string (sha256 fingerprint). Pointer valid until `elysium_stop`.
 */
const char *elysium_get_node_id(struct ElysiumHandle *handle);

/**
 * Returns the node's Curve25519 public key as base64. Pointer valid until `elysium_stop`.
 */
const char *elysium_get_public_key(struct ElysiumHandle *handle);

/**
 * Send an encrypted payload to a peer node. Returns true on success.
 *
 * `payload_encrypted` should be AES-GCM ciphertext produced by the Swift CryptoManager.
 */
bool elysium_send_message(struct ElysiumHandle *handle,
                          const char *recipient_node_id,
                          const unsigned char *payload_encrypted,
                          uintptr_t payload_len);

/**
 * Poll for incoming messages. `callback` is invoked once per queued message (JSON string).
 * This is synchronous — call from a background thread or Swift Task.
 */
void elysium_poll_inbox(struct ElysiumHandle *handle, void (*callback)(const char *msg_json));

/**
 * Resolve a human-readable name to a node_id via the Elysium DHT.
 * Returns null if not found. Caller must NOT free the returned pointer.
 */
const char *elysium_resolve_name(struct ElysiumHandle *handle, const char *name);

/**
 * Number of currently connected peers.
 */
uint32_t elysium_peer_count(struct ElysiumHandle *handle);

/**
 * Whether the node has at least one peer connection.
 */
bool elysium_is_connected(struct ElysiumHandle *handle);

/**
 * Export the node's identity + queued messages to a file bundle (for sneakernet transfer).
 */
bool elysium_export_bundle(struct ElysiumHandle *handle, const char *path);

/**
 * Import a bundle written by `elysium_export_bundle`.
 */
bool elysium_import_bundle(struct ElysiumHandle *handle, const char *path);

#endif /* ELYSIUM_FFI_H */
